version: '3.8'

services:
  api:
    image: lucasgoleiro/techchallenge3
    ports:
      - "8080:8080"
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: tech_challenge_db
